### ISSUE TITLE
remove use of FormData

### ISSUE THREAD

**Issue by quarterto** [Financial-Times/n-feedback#75]
as used [here](https://github.com/Financial-Times/n-feedback/blob/114fe058a216e21345f2ff0f0d823493b2aba7d9/index.js#L125). a few reasons:

- requires the polyfill, which apps now have to install separately when migrating to Page Kit
- it's used in a single place in this component, and to extract data from the form into an object, which can be done other ways, and isn't the full intended use case of `FormData` (which is constructing body objects for `XMLHTTPRequest` or `fetch`)
- `FormData.prototype.forEach` isn't included in the `FormData` spec, it's nonstandard (but happens to be implemented in most browsers that implement `FormData`, as well as the polyfill)

**Comment by JakeChampion** [comment]
Should we have an issue open on polyfill-library for FormData?

**Comment by i-like-robots** [comment]
According to MDN all of the browsers we provide an enhanced experience to (and thus render this component in) support `FormData`.

https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData#Browser_compatibility
